# This is a sample Python script.

# Press Shift+F10 to execute it or replace it with your code.
# Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.
from graphviz import Digraph
def draw():

    g = Digraph('Pratylenchus', filename = 'PratylenchusKey.gv')#, node_attr={'color': 'lightblue2', 'style': 'filled'} )
    #g.attr(size='6,6')
    g.graph_attr['rankdir'] = 'LR'
    g.node('001', label='Pratylenchus')

    g.edge('001','002', label='Labial region with two annuli')
    g.edge('001','028', label='Labial region with three annuli')
    g.edge('001','065', label='Labial region with four annuli')
    g.edge('002','003', label='Males absent, spermatheca empty')
    g.edge('002','008', label='Males generally common, \nspermatheca filled with sperm')
    g.node('P. angulatus', shape='doubleoctagon')
    g.edge('003','P. angulatus', label='Stylet length < 13 μm')
    g.edge('003','004', label='Stylet length > 13 μm')
    g.node('P. acuticaudatus', shape='doubleoctagon')
    g.edge('004','P. acuticaudatus', label='Spermatheca absent or reduced')
    g.edge('004','005', label='Spermatheca well developed')
    g.node('P. crassi', shape='doubleoctagon')
    g.edge('005','P. crassi', label='Vulva position < 75%')
    g.edge('005','006', label='Vulva position &#8805; 75%')
    g.edge('006','007', label='Post-vulval uterine sac < 16 μm')
    g.node('P. hippeastri', shape='doubleoctagon')
    g.edge('006','P. hippeastri', label='Post-vulval uterine sac 30-35 μm long')
    g.node('P. tenuis', shape='doubleoctagon')
    g.edge('007','P. tenuis', label='Female tail tip smooth')
    g.node('P. estoniensis', shape='doubleoctagon')
    g.edge('007','P. estoniensis', label='Female tail tip striated')
    g.node('P. macrostylus', shape='doubleoctagon')
    g.edge('008','P. macrostylus', label='Stylet length > 20 μm')
    g.edge('008','009', label='Stylet length < 20 μm')
    g.edge('009','010', label='Stylet length 18-20 μm')
    g.edge('009','011', label='Stylet length < 18 μm')
    g.node('P. brachyurus', shape='doubleoctagon')
    g.edge('010','P. brachyurus', label='Spermatheca reduced,\nlabial region offset\n from body, \nwith angular anterior margin')
    g.node('P. brzeskii', shape='doubleoctagon')
    g.edge('010','P. brzeskii', label='Spermatheca developed, rectangular')
    g.edge('011','012', label='Stylet length 16-17.9 μm')
    g.edge('011','018', label='Stylet length < 16 μm')
    g.node('P. neglectus', shape='doubleoctagon')
    g.edge('012','P. neglectus', label='Spermatheca reduced, \nsecond annulus of labial \nregion wider thanf irst')
    g.edge('012','013', label='Spermatheca developed')
    g.edge('013','014', label='Spermatheca rounded to spherical')
    g.edge('013','015', label='Spermatheca oval or rectangular')
    g.node('P. flakkensis', shape='doubleoctagon')
    g.node('P. dunensis', shape='doubleoctagon')
    g.edge('014','P. flakkensis', label='Post-vulval uterine sac < 20 μm')
    g.edge('014','P. dunensis', label='Post-vulval uterine sac 25-30 μm')
    g.node('P. yamagutii', shape='doubleoctagon')
    g.edge('015','P. yamagutii', label='Post-vulval uterine sac < 16 μm')
    g.edge('015','016', label='Post-vulval uterine sac > 16 μm')
    g.node('P. panamaensis', shape='doubleoctagon')
    g.edge('016','P. panamaensis', label='Female tail subcylindrical')
    g.edge('016','017', label='Female tail conoid')
    g.node('P. loosi', shape='doubleoctagon')
    g.edge('017', 'P. loosi', label='Pharyngeal overlap < 40 μm,\n labial region rounded, spermathecarectangular,\n tail tapering gradually \nto smooth conical tip,\n usually with narrowly rounded terminus,\n males abundant')
    g.node('P. okinawensis', shape='doubleoctagon')
    g.edge('017','P. okinawensis', label='Pharyngeal overlap > 50 μm')
    g.node('P. hexincisus', shape='doubleoctagon')
    g.edge('018','P. hexincisus', label='Spermatheca reduced, lateral fields with six lines on most of body')
    g.edge('018','019', label='Spermatheca developed')
    g.edge('019','020', label='Spermatheca rounded to spherical')
    g.edge('019','024', label='Spermatheca oval')
    g.node('P. gibbicaudatus', shape='doubleoctagon')
    g.edge('020','P. gibbicaudatus', label='Vulva position < 75%')
    g.edge('020','021', label='Vulva position > 75%')
    g.edge('021','022', label='Post-vulval uterine sac < 20 μm')
    g.node('P. jaehni', shape='doubleoctagon')
    g.edge('021','P. jaehni', label='Post-vulval uterine sac > 20 μm')
    g.node('P. silvaticus', shape='doubleoctagon')
    g.edge('022','P. silvaticus', label='Female tail conoid')
    g.edge('022','023', label='Female tail subcylindrical')
    g.node('P. alleni', shape='doubleoctagon')
    g.edge('023','P. alleni', label='Female tail tip smooth')
    g.node('P. roseus', shape='doubleoctagon')
    g.edge('023','P. roseus', label='Female tail tip striated')
    g.edge('024','025', label='Vulva position < 75%')
    g.edge('024','026', label='Vulva position > 75%')
    g.node('P. artemisiae', shape='doubleoctagon')
    g.edge('025','P. artemisiae', label='Female tail subcylindrical')
    g.node('P. scribneri', shape='doubleoctagon')
    g.edge('025','P. scribneri', label='Female tail conoid, \nlabial region slightly offset from body,\n stylet stout, \nwith rounded knobs, \nspermatheca oblong, \ntail tapering slightly with smooth terminus')
    g.node('P. neobrachyurus', shape='doubleoctagon')
    g.edge('026','P. neobrachyurus', label='Post-vulval uterine sac < 16 μm')
    g.edge('026','027', label='Post-vulval uterine sac > 16 μm')
    g.node('P. coffeae', shape='doubleoctagon')
    g.edge('027','P. coffeae', label='Pharyngeal overlap < 40 μm,\n labial region slightly offset,\n postvulval uterine sac 1.0-1.5 \nbody diam. long with a terminal rudimentary ovary, \nfemale tail tip truncate or hemispherical')
    g.node('P. pseudocoffeae', shape='doubleoctagon')
    g.edge('027','P. pseudocoffeae', label='Pharyngeal overlap > 50 μm')
    g.edge('028','029', label='Males absent, spermatheca empty')
    g.edge('028','043', label='Males generally common, spermatheca filled with sperm')
    g.node('P. microstylus', shape='doubleoctagon')
    g.edge('029','P. microstylus', label='Stylet length < 13 μm')
    g.edge('029','030', label='Stylet length > 13 μm')
    g.edge('030','031', label='Stylet length 18-20 μm')
    g.edge('030','032', label='Stylet length < 18 μm')
    g.node('P. japonicus', shape='doubleoctagon')
    g.edge('031','P. japonicus', label='Post-vulval uterine sac < 20 μm')
    g.node('P. bolivianus', shape='doubleoctagon')
    g.edge('031','P. bolivianus', label='Post-vulval uterine sac > 20 μm')
    g.edge('032','033', label='Stylet length < 16 μm')
    g.edge('032','037', label='Stylet length > 16 μm')
    g.edge('033','034', label='Spermatheca reduced or absent')
    g.node('P. elamini', shape='doubleoctagon')
    g.edge('033','P. elamini', label='Spermatheca oval')
    g.node('P. teres', shape='doubleoctagon')
    g.edge('034','P. teres', label='Vulva position < 75%')
    g.edge('034','035', label='Vulva position > 75%')
    g.edge('035','036', label='Post-vulval uterine sac < 25 μm')
    g.node('P. sensillatus', shape='doubleoctagon')
    g.edge('035','P. sensillatus', label='Post-vulval uterine sac > 25 μm')
    g.node('P. cruciferus', shape='doubleoctagon')
    g.edge('036','P. cruciferus', label='Female tail tip smooth')
    g.node('P. kumaoensis', shape='doubleoctagon')
    g.edge('036','P. kumaoensis', label='Female tail tip striated')
    g.edge('037','038', label='Spermatheca reduced or absent')
    g.edge('037','041', label='Spermatheca developed')
    g.node('P. curvicauda', shape='doubleoctagon')
    g.edge('038','P. curvicauda', label='Vulva position < 75%')
    g.edge('038','039', label='Vulva position > 75%')
    g.node('P. pinguicaudatus', shape='doubleoctagon')
    g.edge('039','P. pinguicaudatus', label='Post-vulval uterine sac < 16 μm')
    g.edge('039','040', label='Post-vulval uterine sac > 20 μm')
    g.node('P. delattrei', shape='doubleoctagon')
    g.edge('040','P. delattrei', label='Female tail tip smooth')
    g.node('P. subranjani', shape='doubleoctagon')
    g.edge('040','P. subranjani', label='Female tail tip striated')
    g.node('P. yassini', shape='doubleoctagon')
    g.edge('041','P. yassini', label='Vulva position < 75%')
    g.edge('041','042', label='Vulva position > 75%')
    g.node('P. arlingtoni', shape='doubleoctagon')
    g.edge('042','P. arlingtoni', label='Post-vulval uterine \nsac shorter than 20 μm')
    g.node('P. andinus', shape='doubleoctagon')
    g.edge('042','P. andinus', label='Post-vulval uterine \nsac longer than 20 μm')
    g.node('P. ekrami', shape='doubleoctagon')
    g.edge('043','P. ekrami', label='Stylet length < 13 μm')
    g.edge('043','044', label='Stylet length > 13 μm')
    g.edge('044','045', label='Stylet length < 16 μm')
    g.edge('044','055', label='Stylet length > 16 μm')
    g.edge('045','046', label='Spermatheca rounded to spherical')
    g.edge('045','049', label='Spermatheca oval or rectangular')
    g.node('P. bhattii', shape='doubleoctagon')
    g.edge('046','P. bhattii', label='Vulva position < 75%')
    g.edge('046','047', label='Vulva position > 75%')
    g.node('P. kralli', shape='doubleoctagon')
    g.edge('047','P. kralli', label='Post-vulval uterine sac < 16 μm')
    g.edge('047','048', label='Post-vulval uterine sac > 16 μm')
    g.node('P. mediterraneus', shape='doubleoctagon')
    g.edge('048','P. mediterraneus', label='Female tail tip smooth')
    g.node('P. pseudofallax', shape='doubleoctagon')
    g.edge('048','P. pseudofallax', label='Female tail tip striated')
    g.edge('049','050', label='Spermatheca oval')
    g.edge('049','053', label='Spermatheca rectangular')
    g.node('P. sudanensis', shape='doubleoctagon')
    g.edge('050','P. sudanensis', label='Vulva position < 75%')
    g.edge('050','051', label='Vulva position > 75%')
    g.edge('051','P. vulnus', label='Post-vulval \nuterine sac > 30 μm, \nlabial region almost continuous with body contour, \npharynx overlapping intestine\n in a long lobe spermatheca oblong, \npost-vulval uterine sac ca 2 vulval body diam. long with rudimentary ovary, \ntail tapering, \nwith narrowly rounded to subacute smooth tip')
    g.edge('051','052', label='Post-vulval uterine sac < 30 μm')
    g.edge('052','P. unzenensis', label='Female tail tip smooth')
    g.edge('052','P. pratensisobrinus', label='Female tail tip striated')
    g.edge('053','054', label='Vulva position < 80%.')
    g.node('P. manaliensis', shape='doubleoctagon')
    g.edge('053','P. manaliensis', label='Vulva position 80-85%')
    g.node('P. pratensis', shape='doubleoctagon')
    g.edge('054','P. pratensis', label='Female tail tip striated, \ncuticle finely annulated, \noval to rectangular spermatheca, \npost-vulval uterine sac \nlength similar to body diam.,\ntail annulated until terminus')
    g.edge('054','Female tail tip with a ventral projection', label='P. ventroprojectus')
    g.edge('055','056', label='Spermatheca reduced or absent')
    g.edge('055','058', label='Spermatheca developed')
    g.node('P. zeae', shape='doubleoctagon')
    g.edge('056','P. zeae', label='Vulva position < 76%, \nspermatheca round, \nvulva at 68-76%, tail \nconoid, terminus generally almost pointed, \nnarrowly rounded to subacute, unstriated')
    g.edge('056','057', label='Vulva position > 76%.')
    g.node('P. thornei', shape='doubleoctagon')
    g.edge('057','P. thornei', label='Female tail tip smooth, \nlabial region not offset from body, \nouter margin of sclerotised labial \nframework conspicuously extending ca two annuli \ninto body and 1 annulus into labial region, \nlateral fields with four lines, \nthe outer ones straight or weakly crenate, \nstylet medium size (17-19 μm long), \nspermatheca difficult to see, \nnot containing spermatozoa, \nmales very rare')
    g.node('P. crenatus', shape='doubleoctagon')
    g.edge('057','P. crenatus', label='Female tail tip striated')
    g.edge('058','059', label='Spermatheca rounded to spherical')
    g.edge('058','062', label='Spermatheca oval')
    g.edge('059','P. convallariae', label='Post-vulval uterine sac longer than 35 μm')
    g.edge('059','060', label='Post-vulval uterine sac between 25-30 μm')
    g.node('P. penetrans', shape='doubleoctagon')
    g.edge('060','P. penetrans', label='Female tail tip smooth, \nlabial region slightly offset, low, \nflat in front, \nwith rounded outer margins, \npharynx overlapping intestine in a lobe ca 1.5 body diam. long, \npost-vulval uterine sac short,\n undifferentiated and tail generally rounded, \ntip smooth')
    g.edge('060','061', label='Female tail tip striated')
    g.node('P. pseudopratensis', shape='doubleoctagon')
    g.edge('061','P. pseudopratensis', label='Spermatheca rectangular, \nfemale tail tip rounded to truncate,\nsmooth')
    g.edge('061','P. fallax', label='Spermatheca rounded, \nfemale tail tip rounded, \nsmooth or slightly irregular contour')
    g.node('P. morettoi', shape='doubleoctagon')
    g.edge('062','P. morettoi', label='Post-vulval uterine sac > 35 μm')
    g.edge('062','063', label='Post-vulval uterine sac < 35 μm')
    g.edge('063','064', label='Female tail tip smooth')
    g.node('P. kasari', shape='doubleoctagon')
    g.edge('063','P. kasari', label='Female tail tip striated')
    g.node('P. subpenetrans', shape='doubleoctagon')
    g.edge('064','P. subpenetrans', label='Post-vulval uterine sac < 20 μm')
    g.node('P. mulchandi', shape='doubleoctagon')
    g.edge('064','P. mulchandi', label='Post-vulval uterine sac > 30 μm')
    g.edge('065','066', label='Males absent, spermatheca empty')
    g.node('P. goodeyi', shape='doubleoctagon')
    g.edge('065','P. goodeyi', label='Males generally common, \nspermatheca filled with sperm, \mlateral fields with four inconspicuous lines, \nthe two outer bands partially areolated, \ntail conoid, ventrally concave')
    g.node('P. typicus', shape='doubleoctagon')
    g.edge('066','P. typicus', label='Post-vulval uterine sac > 30 μm')
    g.node('P. wescolagricus', shape='doubleoctagon')
    g.edge('066','P. wescolagricus', label='Post-vulval uterine sac < 30 μm')


    g.render('NematodaKey.gv', format='svg', view=True)
    g.render('NematodaKey.gv', format='jpg', view=False)
    g.render('NematodaKey.gv', format='pdf', view=False)

def main():
    # Use a breakpoint in the code line below to debug your script.
    draw()


# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    main()

# See PyCharm help at https://www.jetbrains.com/help/pycharm/
